In [1]:
import pandas as pd

df = pd.read_csv("WDICSV.csv")

df.shape

(395276, 70)

In [2]:
df.head(7)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.747222,35.240236,NaN,NaN
5,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,69.115673,70.947036,71.816938,72.955844,74.377118,75.841997,76.277014,79.926473,NaN,NaN
6,Africa Eastern and Southern,AFE,Account ownership at a financial institution o...,FX.OWN.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025'],
      dtype='object')

In [4]:
indicators = [
    "IT.NET.USER.ZS",
    "NY.GDP.PCAP.CD",
    "SP.POP.TOTL"
]

filtered = df[df["Indicator Code"].isin(indicators)]

filtered.to_csv("WDI_Selected.csv", index=False)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395276 entries, 0 to 395275
Data columns (total 70 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Country Name    395276 non-null  object
 1   Country Code    395276 non-null  object
 2   Indicator Name  395276 non-null  object
 3   Indicator Code  395276 non-null  object
 4   1960            37409 non-null   float64
 5   1961            42744 non-null   float64
 6   1962            44022 non-null   float64
 7   1963            44959 non-null   float64
 8   1964            45461 non-null   float64
 9   1965            47288 non-null   float64
 10  1966            47548 non-null   float64
 11  1967            48180 non-null   float64
 12  1968            48780 non-null   float64
 13  1969            49561 non-null   float64
 14  1970            72414 non-null   float64
 15  1971            76752 non-null   float64
 16  1972            78457 non-null   float64
 17  1973            79114 non-null   float64
 18  1974            80558 non-null   float64
 19  1975            84002 non-null   float64
 20  1976            86280 non-null   float64
 21  1977            88718 non-null   float64
 22  1978            89483 non-null   float64
 23  1979            90374 non-null   float64
 24  1980            94578 non-null   float64
 25  1981            96708 non-null   float64
 26  1982            96939 non-null   float64
 27  1983            97885 non-null   float64
 28  1984            98590 non-null   float64
 29  1985            100577 non-null  float64
 30  1986            101542 non-null  float64
 31  1987            101960 non-null  float64
 32  1988            101386 non-null  float64
 33  1989            102972 non-null  float64
 34  1990            129330 non-null  float64
 35  1991            137186 non-null  float64
 36  1992            140200 non-null  float64
 37  1993            142801 non-null  float64
 38  1994            145123 non-null  float64
 39  1995            152088 non-null  float64
 40  1996            152864 non-null  float64
 41  1997            153156 non-null  float64
 42  1998            155861 non-null  float64
 43  1999            161863 non-null  float64
 44  2000            192372 non-null  float64
 45  2001            187560 non-null  float64
 46  2002            190204 non-null  float64
 47  2003            190846 non-null  float64
 48  2004            193937 non-null  float64
 49  2005            203416 non-null  float64
 50  2006            205139 non-null  float64
 51  2007            207773 non-null  float64
 52  2008            207604 non-null  float64
 53  2009            210589 non-null  float64
 54  2010            220938 non-null  float64
 55  2011            217180 non-null  float64
 56  2012            218572 non-null  float64
 57  2013            217345 non-null  float64
 58  2014            222754 non-null  float64
 59  2015            227019 non-null  float64
 60  2016            222801 non-null  float64
 61  2017            220678 non-null  float64
 62  2018            219826 non-null  float64
 63  2019            216813 non-null  float64
 64  2020            214194 non-null  float64
 65  2021            208964 non-null  float64
 66  2022            194261 non-null  float64
 67  2023            177314 non-null  float64
 68  2024            138516 non-null  float64
 69  2025            22603 non-null   float64
dtypes: float64(66), object(4)
memory usage: 211.1+ MB

In [6]:
df1 = pd.read_csv("WDI_Selected.csv")

df1.shape

df1.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1.860892e+02,1.869091e+02,1.973675e+02,2.254001e+02,2.089627e+02,2.268361e+02,...,1.334471e+03,1.528104e+03,1.552074e+03,1.507086e+03,1.351592e+03,1.562416e+03,1.679328e+03,1.571449e+03,1.615396e+03,NaN
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.630000e+01,1.730000e+01,1.960000e+01,2.160000e+01,2.350000e+01,2.500000e+01,2.680000e+01,2.780000e+01,2.880000e+01,30.4
2,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.300757e+08,1.335349e+08,1.371717e+08,1.409455e+08,1.449041e+08,1.490335e+08,...,6.233694e+08,6.400587e+08,6.578011e+08,6.759502e+08,6.944461e+08,7.130909e+08,7.318214e+08,7.504914e+08,7.692809e+08,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,1.219368e+02,1.274510e+02,1.338238e+02,1.390050e+02,1.485459e+02,1.555619e+02,...,1.630039e+03,1.574231e+03,1.720140e+03,2.216385e+03,2.030862e+03,2.112794e+03,2.138473e+03,1.841855e+03,1.411337e+03,NaN
4,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.090000e+01,2.380000e+01,2.570000e+01,2.850000e+01,3.150000e+01,3.470000e+01,3.750000e+01,3.850000e+01,4.000000e+01,42.4

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    798 non-null    object
 1   Country Code    798 non-null    object
 2   Indicator Name  798 non-null    object
 3   Indicator Code  798 non-null    object
 4   1960            415 non-null    float64
 5   1961            418 non-null    float64
 6   1962            420 non-null    float64
 7   1963            420 non-null    float64
 8   1964            420 non-null    float64
 9   1965            426 non-null    float64
 10  1966            427 non-null    float64
 11  1967            431 non-null    float64
 12  1968            432 non-null    float64
 13  1969            432 non-null    float64
 14  1970            454 non-null    float64
 15  1971            455 non-null    float64
 16  1972            455 non-null    float64
 17  1973            455 non-null    float64
 18  1974            455 non-null    float64
 19  1975            459 non-null    float64
 20  1976            459 non-null    float64
 21  1977            462 non-null    float64
 22  1978            461 non-null    float64
 23  1979            462 non-null    float64
 24  1980            472 non-null    float64
 25  1981            472 non-null    float64
 26  1982            473 non-null    float64
 27  1983            473 non-null    float64
 28  1984            475 non-null    float64
 29  1985            477 non-null    float64
 30  1986            477 non-null    float64
 31  1987            484 non-null    float64
 32  1988            487 non-null    float64
 33  1989            487 non-null    float64
 34  1990            713 non-null    float64
 35  1991            545 non-null    float64
 36  1992            557 non-null    float64
 37  1993            573 non-null    float64
 38  1994            600 non-null    float64
 39  1995            650 non-null    float64
 40  1996            683 non-null    float64
 41  1997            695 non-null    float64
 42  1998            702 non-null    float64
 43  1999            709 non-null    float64
 44  2000            713 non-null    float64
 45  2001            717 non-null    float64
 46  2002            724 non-null    float64
 47  2003            717 non-null    float64
 48  2004            720 non-null    float64
 49  2005            754 non-null    float64
 50  2006            756 non-null    float64
 51  2007            759 non-null    float64
 52  2008            759 non-null    float64
 53  2009            761 non-null    float64
 54  2010            760 non-null    float64
 55  2011            764 non-null    float64
 56  2012            761 non-null    float64
 57  2013            759 non-null    float64
 58  2014            760 non-null    float64
 59  2015            759 non-null    float64
 60  2016            760 non-null    float64
 61  2017            757 non-null    float64
 62  2018            739 non-null    float64
 63  2019            746 non-null    float64
 64  2020            740 non-null    float64
 65  2021            736 non-null    float64
 66  2022            737 non-null    float64
 67  2023            730 non-null    float64
 68  2024            720 non-null    float64
 69  2025            43 non-null     float64
dtypes: float64(66), object(4)
memory usage: 436.5+ KB

In [8]:
country = pd.read_csv("WDICountry.csv")

country_small = country[
    ["Country Code", "Region", "Income Group"]
]

df2 = df1.merge(
    country_small,
    on="Country Code",
    how="left"
)

In [9]:
df2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2018,2019,2020,2021,2022,2023,2024,2025,Region,Income Group
0,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1.860892e+02,1.869091e+02,1.973675e+02,2.254001e+02,2.089627e+02,2.268361e+02,...,1.552074e+03,1.507086e+03,1.351592e+03,1.562416e+03,1.679328e+03,1.571449e+03,1.615396e+03,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.960000e+01,2.160000e+01,2.350000e+01,2.500000e+01,2.680000e+01,2.780000e+01,2.880000e+01,30.4,NaN,NaN
2,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.300757e+08,1.335349e+08,1.371717e+08,1.409455e+08,1.449041e+08,1.490335e+08,...,6.578011e+08,6.759502e+08,6.944461e+08,7.130909e+08,7.318214e+08,7.504914e+08,7.692809e+08,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,1.219368e+02,1.274510e+02,1.338238e+02,1.390050e+02,1.485459e+02,1.555619e+02,...,1.720140e+03,2.216385e+03,2.030862e+03,2.112794e+03,2.138473e+03,1.841855e+03,1.411337e+03,NaN,NaN,NaN
4,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.570000e+01,2.850000e+01,3.150000e+01,3.470000e+01,3.750000e+01,3.850000e+01,4.000000e+01,42.4,NaN,NaN

In [10]:
df3 = df2.melt( id_vars=[ 
    "Country Name", "Country Code", "Indicator Name", "Indicator Code", "Region", "Income Group" ], 
    var_name="Year", value_name="Value" )

In [11]:
df3.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Region,Income Group,Year,Value
0,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,1960,1.860892e+02
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,1960,NaN
2,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,NaN,NaN,1960,1.300757e+08
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,1960,1.219368e+02
4,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,1960,NaN

In [12]:
df3 = df3[df3["Region"].notna()]

In [13]:
df3.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Region,Income Group,Year,Value
147,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,Middle East & North Africa,Low income,1960,NaN
148,Afghanistan,AFG,Individuals using the Internet (% of population),IT.NET.USER.ZS,Middle East & North Africa,Low income,1960,NaN
149,Afghanistan,AFG,"Population, total",SP.POP.TOTL,Middle East & North Africa,Low income,1960,9035043.0
150,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,Europe & Central Asia,Upper middle income,1960,NaN
151,Albania,ALB,Individuals using the Internet (% of population),IT.NET.USER.ZS,Europe & Central Asia,Upper middle income,1960,NaN

In [14]:
df3.to_csv("WDI_Cleaned.csv", index=False)

In [17]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42966 entries, 147 to 52667
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    42966 non-null  object
 1   Country Code    42966 non-null  object
 2   Indicator Name  42966 non-null  object
 3   Indicator Code  42966 non-null  object
 4   Region          42966 non-null  object
 5   Income Group    42570 non-null  object
 6   Year            42966 non-null  object
 7   Value           31868 non-null  float64
dtypes: float64(1), object(7)
memory usage: 3.0+ MB

In [18]:
df3["Year"] = pd.to_numeric(df3["Year"])

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42966 entries, 147 to 52667
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    42966 non-null  object
 1   Country Code    42966 non-null  object
 2   Indicator Name  42966 non-null  object
 3   Indicator Code  42966 non-null  object
 4   Region          42966 non-null  object
 5   Income Group    42570 non-null  object
 6   Year            42966 non-null  int64
 7   Value           31868 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.0+ MB

In [20]:
df3 = df3[df3["Year"] >= 2000]

In [21]:
df3.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Region,Income Group,Year,Value
32067,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,Middle East & North Africa,Low income,2000,1.749310e+02
32068,Afghanistan,AFG,Individuals using the Internet (% of population),IT.NET.USER.ZS,Middle East & North Africa,Low income,2000,NaN
32069,Afghanistan,AFG,"Population, total",SP.POP.TOTL,Middle East & North Africa,Low income,2000,2.013033e+07
32070,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,Europe & Central Asia,Upper middle income,2000,1.160420e+03
32071,Albania,ALB,Individuals using the Internet (% of population),IT.NET.USER.ZS,Europe & Central Asia,Upper middle income,2000,1.140973e-01

In [22]:
df3.duplicated().sum()

np.int64(0)

In [23]:
df3.to_csv("WDI_Cleaned_Final.csv", index=False)